### ISSUE TITLE
silent embedded elasiticsearch error

### ISSUE THREAD

**Issue by ror6ax** [pblittle/docker-logstash#100]
I have a following error in Kibana:
`
Possibility #1: Your elasticsearch server is down or unreachable
This can be caused by a network outage, or a failure of the Elasticsearch process. If you have recently run a query that required a terms facet to be executed it is possible the process has run out of memory and stopped. Be sure to check your Elasticsearch logs for any sign of memory pressure.
Possibility #2: You are running Elasticsearch 1.4 or higher
`

elasticsearch in indeed unreachable but the logs are silent.

**Comment by pblittle** [comment]
@ror6ax thank you for reporting this issue. Before we can move forward I will need enough information to be able to reproduce the issue. Please provide a sample configuration file and the exact commands you ran to produce the error reported.

**Comment by ror6ax** [comment]
The exact command I use is as follows: 
`docker run -d -p 9292:9292   -p 9200:9200 -p 5000:5000 -v /root/01-lumberjack-input.conf:/opt/logstash/conf.d/01-lumberjack-input.conf -v /etc/pki/tls/certs/logstash-forwarder.crt:/etc/pki/tls/certs/logstash-forwarder.crt -v /etc/pki/tls/private/logstash-forwarder.key:/etc/pki/tls/private/logstash-forwarder.key -v /tmp/ls.log:/var/log/logstash/logstash.log  pblittle/docker-logstash`

No other alterations.

ip:9200 does not show Elasticsearch usual JSON string and when I attach to container I cannot see the process running. The only process there is happens to be Logstash:

`
/usr/bin/java-Xmx500m-XX:+UseParNewGC-XX:+UseConcMarkSweepGC-Djava.awt.headless=true-XX:CMSInitiatingOccupancyFraction=75-XX:+UseCMSInitiatingOccupancyOnly-jar/opt/logstash/vendor/jar/jruby-complete-1.7.17.jar-I/opt/logstash/lib/opt/logstash/lib/logstash/runner.rbagent--config/opt/logstash/conf.d/**/*.conf--log/var/log/logstash/logstash.log--we
`

**Comment by zmsp** [comment]
Hi, I have the same issue. I was using default config ELK. Also tried custom config with shared container, same issue. Thanks

**Comment by pblittle** [comment]
@zmsp, thanks for chiming in. Are you saying that when you run the basic documented [1] run command you don't have a successfully deployed ELK stack?

```
$ docker run -d \
  -p 9292:9292 \
  -p 9200:9200 \
  pblittle/docker-logstash
```

```
$ docker ps
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS              PORTS                                            NAMES
ee5e6084f781        pblittle/docker-logstash   "/app/bin/boot"     About an hour ago   Up About an hour    0.0.0.0:9200->9200/tcp, 0.0.0.0:9292->9292/tcp   adoring_goodall
```

```
$ curl -I http://192.168.59.103:9292/index.html#/dashboard/file/guided.json
HTTP/1.1 200 OK
content-type: text/html;charset=utf-8
content-length: 2073
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
```

```
$ curl -XGET 192.168.59.103:9200/
{
  "status" : 200,
  "name" : "Oracle",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.0",
    "build_hash" : "929b9739cae115e73c346cb5f9a6f24ba735a743",
    "build_timestamp" : "2015-07-16T14:31:07Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

Do you not see similar results?

[1] https://github.com/pblittle/docker-logstash#full-elk-stack-default

**Comment by zmsp** [comment]
My issue was resolved. 

But I think the issue was due to browser serving the fail to connect to elasticserch from cache which started when I did custom config for logstash. 

Thanks for making this!

**Comment by pblittle** [comment]
@zmsp I'm glad to hear you resolved the issue. You're welcome. I'm glad you're finding it useful!

I'm still curious about why the container didn't run successfully the first time. Do you have any additional insight? It seems like there are a number of odd issues that pop up randomly for other folks also. I would love to find the root cause and fix the issue.

**Comment by zmsp** [comment]
I used custom config for logstash first which had some error. This resulted in the failed page. Then I tried the default config and it was serving the error page for some reason. As soon as I used a different browser it was fixed.

This error also shows up during the first minute of when you start the container which I think due to elasticsearch server taking it's time while starting.

**Comment by pblittle** [comment]
@zmsp thanks for the insight. This is sounding more and more like a timing issue. I am going to close the issue. Please reopen if you experience the problem again.

cc: @ror6ax please take a look at my comments above. Hopefully your issue was timing related also. Please reopen this issue if you think something else is going on.
