### ISSUE TITLE
Logs not shown in Kibana

### ISSUE THREAD

**Issue by RajibBiswasTibco** [pblittle/docker-logstash#112]
I ran the following command in DockerToolbox (Windows):
docker run -d -p 9292:9292 -p 9200:9200 pblittle/docker-logstash
(so I am using the default conf file)

But after that when I run some other containers in DockerToolbox, I don't see any logs in Kibaba at: 
http://192.168.99.100:9292/index.html#/dashboard/file/logstash.json
I also checked following link, it is also empty ( {} ):
http://192.168.99.100:9200/_aliases?pretty

Am I doing something wrong?

My docker version is:
`$ docker version
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 02:47:26 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64`

Let me know if you need any other details from my environment.

**Comment by RajibBiswasTibco** [comment]
Hi @pblittle , Any update on this?

**Comment by pblittle** [comment]
@RajibBiswasTibco I'm sorry for the delay. I'll take a look at your question this evening and will get back to you. Thanks for your patience.

**Comment by pblittle** [comment]
@RajibBiswasTibco, are your containers using a Docker logging driver (`--log-driver`) to ship their logs to the logstash container? It sounds like that configuration might be missing.

https://docs.docker.com/engine/admin/logging/overview

Please let me know if you are already using a logging driver and think the issue is on my end.
