### ISSUE TITLE
sed: -e expression #4, char 16: unknown option to `s'

### ISSUE THREAD

**Issue by jwalton** [pblittle/docker-logstash#55]
When I try to run with 0.11.0, I get:

````
vagrant@vagrant-ubuntu-trusty-64:~$ sudo docker run -it --rm --link elasticsearch:es -p 5000:5000 -v /opt/logstash/logstash.conf:/opt/logstash.conf -v /opt/logstash/ssl:/opt/ssl -v /var/log:/opt/log pblittle/docker-logstash
converted 'https://gist.githubusercontent.com/pblittle/1b7a2f02cd16fa1c58e9/raw/logstash_nxt.conf' (ANSI_X3.4-1968) -> 'https://gist.githubusercontent.com/pblittle/1b7a2f02cd16fa1c58e9/raw/logstash_nxt.conf' (UTF-8)
--2015-02-13 19:58:22--  https://gist.githubusercontent.com/pblittle/1b7a2f02cd16fa1c58e9/raw/logstash_nxt.conf
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 23.235.46.133
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|23.235.46.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 680 [text/plain]
Saving to: '/opt/logstash/conf.d/logstash.conf'

/opt/logstash/conf.d/logstash.conf                                100%[=============================================================================================================================================================>]     680  --.-KB/s   in 0s

2015-02-13 19:58:28 (15.9 MB/s) - '/opt/logstash/conf.d/logstash.conf' saved [680/680]

sed: -e expression #4, char 16: unknown option to `s'
````

**Comment by pblittle** [comment]
@jwalton, first off, your blog post was great. It's cool to see how you're using the image. I had planned on sending you a PR with a small tweak to your `run` command. 

Starting with version `0.11.0`, config files are now stored in `/opt/logstash/conf.d`. This change will allow you to load a directory of config files rather than being tied to `/opt/logstash/logstash.conf`. I did my best to [communicate the change](https://github.com/pblittle/docker-logstash/blob/rel-0.11.0/README.md), but there was no way everyone would know about it.

Having said that, the first issue I see in your command is that you're using the previous location in your volume mount, `-v /opt/logstash/logstash.conf:/opt/logstash.conf`. I don't think this is the root of the issue though. Your incorrect location would cause the [default config file](https://gist.githubusercontent.com/pblittle/1b7a2f02cd16fa1c58e9/raw/logstash_nxt.conf) to be downloaded and used instead.

This leads me to believe that there is either a bug in the default config file or in the code. I was able to reproduce the issue locally:

````
vagrant@ubuntu-14:/vagrant$ sudo docker run -it --rm --link elasticsearch:es -p 5000:5000 -v /opt/logstash/logstash.conf:/opt/logstash/conf.d/logstash.conf -v /opt/logstash/ssl:/opt/ssl -v /var/log:/opt/log pblittle/docker-logstash
sed: -e expression #4, char 16: unknown option to `s'
````
I'll dig in over the weekend and see what I can come up with. Oddly enough, I actually tested this release with your blog post config.

**Comment by jwalton** [comment]
Thanks!  I'll be sure to update my blog post with your new config file stuff.  :)

We're using your docker-logstash in production right now to collect logs from all our servers (along with a custom [stream for bunyan](https://github.com/benbria/node-bunyan-lumberjack)) so thanks very much for building this awesome docker image in the first place.  :)

**Comment by pblittle** [comment]
@jwalton, wow, that's really cool. Thanks for letting me know. I hope I didn't bring your Production cluster down. :)

If you have a minute, do you mind taking a look at my proposed enhancement in issue #49? I'd love to hear your thoughts on the new approach.

**Comment by pblittle** [comment]
@jwalton do you mind testing the #58 hotfix against your configs?

**Comment by jwalton** [comment]
No, you didn't bring down our production machine, just a vagrant VM.  :)  You did convince me I should explicitly declare the tag of all my dependencies though.

I'll have a look at #58 when I get a moment.
