### ISSUE TITLE
ES_PORT placeholder is replaced with invalid value

### ISSUE THREAD

**Issue by systemfreund** [pblittle/docker-logstash#59]
I'm using ES_HOST and ES_PORT in my logstash.conf, but the latter placeholder gets replaced by the value below when I start the container:

    elasticsearch {
        host => "172.17.0.17"
        port => "tcp://172.17.0.17:9200"
        protocol => "http"
    }

**Comment by systemfreund** [comment]
root@104c28ef7bec:/# env
    HOSTNAME=104c28ef7bec
   TERM=xterm
    ES_PORT_9300_TCP=tcp://172.17.0.8:9300
ES_ENV_CA_CERTIFICATES_JAVA_VERSION=20140324
ES_PORT_9300_TCP_PORT=9300
ES_PORT_9200_TCP=tcp://172.17.0.8:9200
ES_PORT_9300_TCP_PROTO=tcp
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ES_ENV_JAVA_VERSION=8u40~b22
PWD=/
ES_ENV_ELASTICSEARCH_VERSION=1.4.3
ES_PORT_9200_TCP_PROTO=tcp
ES_ENV_JAVA_DEBIAN_VERSION=8u40~b22-2
JAVA_VERSION=7u71
SHLVL=1
HOME=/root
JAVA_DEBIAN_VERSION=7u71-2.5.3-2
ES_PORT_9200_TCP_ADDR=172.17.0.8
ES_PORT_9300_TCP_ADDR=172.17.0.8
ES_PORT=tcp://172.17.0.8:9200
ES_PORT_9200_TCP_PORT=9200
ES_NAME=/logstash/es
_=/usr/bin/env

**Comment by systemfreund** [comment]
According to https://docs.docker.com/userguide/dockerlinks/#environment-variables `ES_PORT` will always have a format like `y://x.x.x.x:zzzz`. Can't we just use the value of `ES_PORT_9200_TCP_PORT` like you do in elasticsearch.sh without overriding it when `ES_PORT` is set (which is always true, when linking is used)

**Comment by pblittle** [comment]
@systemfreund when a port env var is returned in the format you noted, `tcp://172.17.0.17:9200`, it is usually because the container link wasn't created. Do you mind verifying that the link was created?

**Comment by systemfreund** [comment]
Are you sure? Because accoring to the documentation the value is as expected:

"Finally, there will be an environment variable called <alias>_PORT that will contain the URL of the first exposed port of the source container. For example, WEBDB_PORT=tcp://172.17.0.82:8080."

**Comment by pblittle** [comment]
@systemfreund this is really interesting. Thanks for continuing to question my logic. :smile: It turns out that I am setting an `ES_PORT` environment variable also. That is obviously creating a conflict. I didn't know that Docker created an `*_PORT` variable. That variable exists on my end to allow the use of an external Elasticsearch server, rather than embedded or linked.

To fix the issue, I'll need to rename my `ES_PORT` variable to avoid the conflict.

```shell
function es_port() {
    local default_port=${ES_PORT_9200_TCP_PORT:-9200}
    local port=${ES_PORT:-$default_port}

    echo "$port"
}
```

https://github.com/pblittle/docker-logstash/blob/master/1.4/base/elasticsearch.sh#L18-L23

Given Kibana isn't able to link (yet?) it is handled differently:

```shell
function kibana_es_port() {
    local port=${ES_PORT:-9200}

    echo "$port"
}
```

https://github.com/pblittle/docker-logstash/blob/master/1.4/base/kibana.sh#L17-L21

Again, great find. I appreciate it. Let me know what you think and/or if you have any additional thoughts.

**Comment by pblittle** [comment]
@systemfreund do you mind giving me the commands you're using to cause this issue? I want to try to reproduce over here.
