### ISSUE TITLE
Securing Kibana

### ISSUE THREAD

**Issue by SyRenity** [pblittle/docker-logstash#83]
Is there an option to add Kibana security via Nginx, for example like in the following?
http://technosophos.com/2014/03/19/ssl-password-protection-for-kibana.html

**Comment by pblittle** [comment]
@SyRenity, I think your best bet is to use a separate Kibana/Nginx image rather than the Kibana install that is embedded in Logstash. Sorry I can't help more. I haven't done this personally, so I don't have any real world experience to offer.

I'm going to close this issue for now. Please reopen if you have any questions specific to the Logstash side of the equation.
